config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  resources :blogs
  resources :classvideos
  resources :professionalvideos

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
end

app/models/classvideo.rb
class Classvideo < ActiveRecord::Base
	belongs_to :user
	# has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>"}
	has_attached_file :video
	# has_attached_file :video, :styles => { 
	# 	:medium => {:geometry => "640x480", :format => 'flv'},
	# 	:thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10 }
	# }, :processors => [:transcoder]
	# validates_attachment_content_type :image,  :content_type => [ "image/jpg", "image/jpeg", "image/png", "image/gif"]
	validates_attachment_content_type :video, :content_type => ["video/mp4", "video.mov", "video/mpeg","video/mpeg4", "image/jpg", "image/jpeg"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def index
		@blogs = Blog.all
	end

	def new
		@blog = Blog.new
	end

	def show
		@blog = blog.find params[:id]
	end
	
	def edit
		@blog = Blog.find params[:id]
	end	

	def update
		@blog = Blog.find params[:id]
		@blog.update_attributes blog_params
		redirect_to blogs_path
	end
	
	def create
		@blog = Blog.create blog_params
		redirect_to blogs_path
	end	

	def destroy
		@blog = Blog.find params[:id]
		@blog.delete
		redirect_to blogs_path
	end	

private
	def blog_params
		params.require(:blog).permit(
			:title,
			:post,
			:date
			)
	end
end

app/controllers/classvideos_controller.rb
class ClassvideosController < ApplicationController

	def index
		@classvideos = Classvideo.all
	end

	def new
		@classvideo = Classvideo.new
	end
	
	def edit
		@classvideo = Classvideo.find params[:id]
	end	

	def update
		@classvideo = Classvideo.find params[:id]
		@classvideo.update_attributes classvideo_params
		redirect_to classvideos_path
	end
	
	def create
		@classvideo = Classvideo.new(classvideo_params)
		if @classvideo.save
			redirect_to classvideos_path
		else
			render "new"
		end		
	end	

	def destroy
		@classvideo = Classvideo.find params[:id]
		@classvideo.delete
		redirect_to classvideos_path
	end	

private
	def classvideo_params
		params.require(:classvideo).permit(
			:video
			)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
	
end

end

app/controllers/professionalvideos_controller.rb
class ProfessionalvideosController < ApplicationController

	def index
		@professionalvideos = Professionalvideo.all
	end

	def new
		@professionalvideo = Professionalvideo.new
	end

	def show
		@professionalvideo = professionalvideo.find params[:id]
	end
	
	def edit
		@professionalvideo = Professionalvideo.find params[:id]
	end	

	def update
		@professionalvideo = Professionalvideo.find params[:id]
		@professionalvideo.update_attributes professionalvideo_params
		redirect_to professionalvideo_path
	end
	
	def create
		@professionalvideo = Professionalvideo.create professionalvideo_params
		redirect_to professionalvideos_path
	end	

	def destroy
		@professionalvideo = Professionalvideo.find params[:id]
		@professionalvideo.delete
		redirect_to professionalvideos_path
	end	

private
	def blog_params
		params.require(:professionalvideo).permit(
			:photo,
			:post
			)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/classvideos_helper.rb
module ClassvideosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professionalvideos_helper.rb
module ProfessionalvideosHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
	<div class="form">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :post %>
    <%= f.text_area :post %>
    <br>
    <%= f.label :date %>
    <%= f.date_field :date %>
    <br>
    <%= f.submit %>
  </div>
<%end%>    

app/views/blogs/index.html.erb
<% @blogs.each do |blog|%>
	<div class="containerblog">
	<li class="innercontainer" style="list-style-type: none; font-size: 20px;">
	<%= blog.title %>
		<br>
		<br>
		<%= blog.post %>
		<br>
		<br>
		<%= blog.date %>
		<br>
		<br>
		<% if user_signed_in? %>
		<%= link_to "Edit", edit_blog_path(blog) %>
		<%= link_to "Delete", blog_path(blog), method: :delete %>
		<% end %>
	</li>
	<p>
	<p>
</div>
<br>
<br>
<%end%>

app/views/classvideos/_form.html.erb
<%= form_for @classvideo, html: { multipart: true } do |f| %>
	<div class="form">   
    <%= f.label :video %>
    <%= f.file_field :video %>
    <br>
    <br>
    <%= f.submit %>
  </div>
<%end%> 

app/views/classvideos/edit.html.erb
<%= render 'form' %>

app/views/classvideos/index.html.erb
<% @classvideos.each do |c|%>
	<div class="containerblog">
	<li class="innercontainer" style="list-style-type: none; font-size: 20px;">
		<video controls src="<%= c.video.url %>">
		</video>
		<br>

		<% if user_signed_in? %>
		<%= link_to "Edit", edit_classvideo_path(c) %>
		<%= link_to "Delete", classvideo_path(c), method: :delete %>
		<% end %>
	</li>
	<p>
	<p>
</div>
<br>
<br>
<%end%>

app/views/classvideos/new.html.erb
<%= render 'form' %>

app/views/home/index.html.erb
<div class="one">
	<%= image_tag('kenyapush.png', :class => 'push') %>
</div>


<div class="two" style="text-align: center;">
	<div class="grid-about">
		<%= image_tag('walk.png', :class => 'kenyaabout') %>
	</div>
<div class="grid-about">
		<%= link_to image_tag('walk.png', :class => 'kenyaabout'), blogs_path %>
	</div>
</div>



<div class="one">
	<div class="grid-class">
		<%= image_tag('class.png', :class => 'teach') %>
	</div>
	<div class="grid-about">
		<%= link_to image_tag('walk.png', :class => 'kenyaabout'), classvideos_path %>
	</div>
</div>


<!-- <div class="contact">
	<div class="container">
		<div class="container1">
		<p></p>
	</div>
	</div>
</div> -->


<div class="social" style="margin-bottom: 70px;">
	<div class="grid-insta" style="border: rgb(36, 36, 36) solid 8px;">
		<!-- INSTANSIVE WIDGET --><script src="//instansive.com/widget/js/instansive.js"></script><iframe src="//instansive.com/widgets/1f35519f4aea559efbe9d801658745f7851e5c98.html" id="instansive_1f35519f4a" name="instansive_1f35519f4a"  scrolling="no" allowtransparency="true" class="instansive-widget" style="border: 0; overflow: hidden;"></iframe>
	</div>
		<div class="grid-insta" style="border: rgb(36, 36, 36) solid 8px;">
		<!-- INSTANSIVE WIDGET --><script src="//instansive.com/widget/js/instansive.js"></script><iframe src="//instansive.com/widgets/1f35519f4aea559efbe9d801658745f7851e5c98.html" id="instansive_1f35519f4a" name="instansive_1f35519f4a"  scrolling="no" allowtransparency="true" class="instansive-widget" style="border: 0; overflow: hidden;"></iframe>
	</div>
	<div class="grid-insta" style="border: rgb(36, 36, 36) solid 8px;">
		<!-- INSTANSIVE WIDGET --><script src="//instansive.com/widget/js/instansive.js"></script><iframe src="//instansive.com/widgets/1f35519f4aea559efbe9d801658745f7851e5c98.html" id="instansive_1f35519f4a" name="instansive_1f35519f4a"  scrolling="no" allowtransparency="true" class="instansive-widget" style="border: 0; overflow: hidden;"></iframe>
	</div>
</div>

app/views/layouts/_nav.html.erb
<div class="nav" style="margin-bottom: 20px;">
	
	<ul>	
		<a href="/"><li><%= image_tag('kenya.png', :class => 'characterpic') %></li></a>
		<li>Kenya Clay</h1>
		<!-- <li>800.989.0000</li>
		<li>madeupemail@gmail.com</li>
		<li>About Me</li>
		<li>Blog</li>
		<li>Videos</li> -->
		<% if user_signed_in? %>
		<li><%= link_to "Add Post", new_blog_path %></li>
		<li><%= link_to "Add Class Video", new_classvideo_path %></li>
<li><%=link_to "Logout", destroy_user_session_path, method: :delete %></li>

		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kenya</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<%= yield %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</body>
</html>